<a href="https://colab.research.google.com/github/cannin/gsoc_2023_pytorch_pathway_commons/blob/main/Match_between_data_clinical_patient_txt%2C_data_clinical_sample_txt%2C_and_data_mrna_seq_v2_rsem_txt_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data_sample = pd.read_csv("/content/drive/MyDrive/gsoc data/data_clinical_sample.txt", sep="\t")

In [3]:
data_sample.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
0,#Identifier to uniquely specify a patient.,A unique sample identifier.,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Numeric value to express the degree of abnorma...,Tissue prospective collection indicator.,Tissue retrospective collection indicator.,Tissue Source Site Code,Text term that describes the anatomic site of ...,Aneuploidy Score,"The type of sample (i.e., normal, primary, met...",MSI Score reported by MANTIS. The suggested th...,MSI Score reported by MSIsensor. The suggested...,Somatic Status,TMB (nonsynonymous),"A Tissue Source Site collects samples (tissue,..."
1,#STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,NUMBER,STRING,NUMBER,NUMBER,STRING,NUMBER,STRING
2,#1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,1,1,1
3,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE_CODE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS,TISSUE_SOURCE_SITE
4,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,2,Primary,0.275,0,Matched,0.8,University of Michigan

In [4]:
ds1 = data_sample.drop([0,1,2,3])
ds1.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type,Cancer Type Detailed,Tumor Type,Neoplasm Histologic Grade,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
4,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,2,Primary,0.275,0,Matched,0.8,University of Michigan
5,TCGA-OR-A5J2,TCGA-OR-A5J2-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,10,Primary,0.3236,1.57,Matched,0.966666667,University of Michigan
6,TCGA-OR-A5J3,TCGA-OR-A5J3-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,12,Primary,0.3434,1.82,Matched,0.333333333,University of Michigan
7,TCGA-OR-A5J4,TCGA-OR-A5J4-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,17,Primary,0.2997,0.45,Matched,3.866666667,University of Michigan
8,TCGA-OR-A5J5,TCGA-OR-A5J5-01,ACC,Adrenocortical Carcinoma,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",NaN,No,Yes,OR,Adrenal Gland,33,Primary,0.5224,5.38,Matched,11.86666667,University of Michigan

In [5]:
ds1.shape

(92, 18)

In [6]:
# Extract the columns of interest
sample1 = ds1['Cancer Type Detailed']
sample2 = ds1['Cancer Type']

# Check if the two columns contain the same values
are_equal = sample1.equals(sample2)

if are_equal:
    print("The columns contain the same values.")
else:
    print("The columns do not contain the same values.")

The columns contain the same values.

In [7]:
ds1.isnull().sum()

#Patient Identifier                           0
Sample Identifier                             0
Oncotree Code                                 0
Cancer Type                                   0
Cancer Type Detailed                          0
Tumor Type                                    0
Neoplasm Histologic Grade                    92
Tissue Prospective Collection Indicator       0
Tissue Retrospective Collection Indicator     0
Tissue Source Site Code                       0
Tumor Disease Anatomic Site                   0
Aneuploidy Score                              3
Sample Type                                   0
MSI MANTIS Score                              1
MSIsensor Score                               1
Somatic Status                                0
TMB (nonsynonymous)                           1
Tissue Source Site                            0
dtype: int64

In [8]:
cleaned_ds = ds1.dropna(axis=1, how='all')
cleaned_ds.isnull().sum()

#Patient Identifier                          0
Sample Identifier                            0
Oncotree Code                                0
Cancer Type                                  0
Cancer Type Detailed                         0
Tumor Type                                   0
Tissue Prospective Collection Indicator      0
Tissue Retrospective Collection Indicator    0
Tissue Source Site Code                      0
Tumor Disease Anatomic Site                  0
Aneuploidy Score                             3
Sample Type                                  0
MSI MANTIS Score                             1
MSIsensor Score                              1
Somatic Status                               0
TMB (nonsynonymous)                          1
Tissue Source Site                           0
dtype: int64

In [9]:
cleaned_ds = cleaned_ds.fillna(method='ffill')

In [10]:
cleaned_ds = cleaned_ds.drop(columns='Cancer Type')

In [11]:
cleaned_ds.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type Detailed,Tumor Type,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,Sample Type,MSI MANTIS Score,MSIsensor Score,Somatic Status,TMB (nonsynonymous),Tissue Source Site
4,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,2,Primary,0.275,0,Matched,0.8,University of Michigan
5,TCGA-OR-A5J2,TCGA-OR-A5J2-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,10,Primary,0.3236,1.57,Matched,0.966666667,University of Michigan
6,TCGA-OR-A5J3,TCGA-OR-A5J3-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,12,Primary,0.3434,1.82,Matched,0.333333333,University of Michigan
7,TCGA-OR-A5J4,TCGA-OR-A5J4-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,17,Primary,0.2997,0.45,Matched,3.866666667,University of Michigan
8,TCGA-OR-A5J5,TCGA-OR-A5J5-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,33,Primary,0.5224,5.38,Matched,11.86666667,University of Michigan

In [12]:
data_patient = pd.read_csv("/content/drive/MyDrive/gsoc data/data_clinical_patient.txt", sep="\t")

In [13]:
dcp = data_patient.drop([0,1,2,3])
dcp.head()

,#Patient Identifier,Subtype,TCGA PanCanAtlas Cancer Type Acronym,Other Patient ID,Diagnosis Age,Sex,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,...,Patient Weight,In PanCan Pathway Analysis,Overall Survival Status,Overall Survival (Months),Disease-specific Survival status,Months of disease-specific survival,Disease Free Status,Disease Free (Months),Progression Free Status,Progress Free Survival (Months)
4,TCGA-OR-A5J1,ACC,ACC,B3164F7B-C826-4E08-9EE6-8FF96D29B913,58,Male,STAGE II,NaN,NaN,-21496,...,NaN,Yes,1:DECEASED,44.54745701,1:DEAD WITH TUMOR,44.54745701,1:Recurred/Progressed,24.78876944,1:PROGRESSION,24.78876944
5,TCGA-OR-A5J2,ACC,ACC,8E7C2E31-D085-4B75-A970-162526DD07A0,44,Female,STAGE IV,NaN,NaN,-16090,...,NaN,Yes,1:DECEASED,55.13364237,1:DEAD WITH TUMOR,55.13364237,NaN,NaN,1:PROGRESSION,9.50126574
6,TCGA-OR-A5J3,ACC,ACC,DFD687BC-6E69-42F7-AF94-D17FC150D1A1,23,Female,STAGE III,NaN,2091,-8624,...,NaN,Yes,0:LIVING,68.74445212,0:ALIVE OR DEAD TUMOR FREE,68.74445212,1:Recurred/Progressed,1.742446658,1:PROGRESSION,1.742446658
7,TCGA-OR-A5J4,NaN,ACC,5F3E2974-F1DF-47A2-8A8A-29BB525EEEF6,23,Female,STAGE IV,NaN,NaN,-8451,...,NaN,No,1:DECEASED,13.90669691,1:DEAD WITH TUMOR,13.90669691,NaN,NaN,1:PROGRESSION,4.142420357
8,TCGA-OR-A5J5,ACC,ACC,802DBD0D-EF07-4C91-AB8D-1DD39532E947,30,Male,STAGE III,NaN,NaN,-11171,...,NaN,Yes,1:DECEASED,11.9998685,1:DEAD WITH TUMOR,11.9998685,NaN,NaN,1:PROGRESSION,1.643817602

In [14]:
dcp.isnull().sum()

#Patient Identifier                                                                             0
Subtype                                                                                        16
TCGA PanCanAtlas Cancer Type Acronym                                                            0
Other Patient ID                                                                                0
Diagnosis Age                                                                                   0
Sex                                                                                             0
Neoplasm Disease Stage American Joint Committee on Cancer Code                                  2
American Joint Committee on Cancer Publication Version Type                                    92
Last Communication Contact from Initial Pathologic Diagnosis Date                              31
Birth from Initial Pathologic Diagnosis Date                                                    0
Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value                          0
Ethnicity Category                                                                             44
Form completion date                                                                            0
Neoadjuvant Therapy Type Administered Prior To Resection Text                                   0
ICD-10 Classification                                                                           0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code     0
International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code          0
Informed consent verified                                                                       0
New Neoplasm Event Post Initial Therapy Indicator                                               9
American Joint Committee on Cancer Metastasis Stage Code                                       92
Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code                       2
American Joint Committee on Cancer Tumor Stage Code                                             2
Person Neoplasm Cancer Status                                                                   2
Primary Lymph Node Presentation Assessment                                                     17
Prior Diagnosis                                                                                 0
Race Category                                                                                  11
Radiation Therapy                                                                               3
Patient Weight                                                                                 92
In PanCan Pathway Analysis                                                                      0
Overall Survival Status                                                                         1
Overall Survival (Months)                                                                       1
Disease-specific Survival status                                                                3
Months of disease-specific survival                                                             1
Disease Free Status                                                                            39
Disease Free (Months)                                                                          39
Progression Free Status                                                                         1
Progress Free Survival (Months)                                                                 1
dtype: int64

In [15]:
dcp['Overall Survival (Months)'] = dcp['Overall Survival (Months)'].fillna(method='ffill')

In [16]:
dcp = dcp.dropna(how='any', axis=1)

In [17]:
dcp.head()

,#Patient Identifier,TCGA PanCanAtlas Cancer Type Acronym,Other Patient ID,Diagnosis Age,Sex,Birth from Initial Pathologic Diagnosis Date,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Form completion date,Neoadjuvant Therapy Type Administered Prior To Resection Text,ICD-10 Classification,"International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code","International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code",Informed consent verified,Prior Diagnosis,In PanCan Pathway Analysis,Overall Survival (Months)
4,TCGA-OR-A5J1,ACC,B3164F7B-C826-4E08-9EE6-8FF96D29B913,58,Male,-21496,0,4/2/14,No,C74.0,8370/1,C74.0,Yes,No,Yes,44.54745701
5,TCGA-OR-A5J2,ACC,8E7C2E31-D085-4B75-A970-162526DD07A0,44,Female,-16090,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,55.13364237
6,TCGA-OR-A5J3,ACC,DFD687BC-6E69-42F7-AF94-D17FC150D1A1,23,Female,-8624,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,68.74445212
7,TCGA-OR-A5J4,ACC,5F3E2974-F1DF-47A2-8A8A-29BB525EEEF6,23,Female,-8451,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,No,13.90669691
8,TCGA-OR-A5J5,ACC,802DBD0D-EF07-4C91-AB8D-1DD39532E947,30,Male,-11171,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,11.9998685

In [18]:
merged_df = pd.merge(cleaned_ds, dcp, on='#Patient Identifier')

In [19]:
merged_df.head()

,#Patient Identifier,Sample Identifier,Oncotree Code,Cancer Type Detailed,Tumor Type,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site Code,Tumor Disease Anatomic Site,Aneuploidy Score,...,Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value,Form completion date,Neoadjuvant Therapy Type Administered Prior To Resection Text,ICD-10 Classification,"International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code","International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code",Informed consent verified,Prior Diagnosis,In PanCan Pathway Analysis,Overall Survival (Months)
0,TCGA-OR-A5J1,TCGA-OR-A5J1-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,2,...,0,4/2/14,No,C74.0,8370/1,C74.0,Yes,No,Yes,44.54745701
1,TCGA-OR-A5J2,TCGA-OR-A5J2-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,10,...,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,55.13364237
2,TCGA-OR-A5J3,TCGA-OR-A5J3-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,12,...,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,68.74445212
3,TCGA-OR-A5J4,TCGA-OR-A5J4-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,17,...,0,12/2/13,No,C74.0,8370/3,C74.0,Yes,No,No,13.90669691
4,TCGA-OR-A5J5,TCGA-OR-A5J5-01,ACC,Adrenocortical Carcinoma,"Adrenocortical Carcinoma, Usual Type",No,Yes,OR,Adrenal Gland,33,...,0,12/3/13,No,C74.0,8370/3,C74.0,Yes,No,Yes,11.9998685

In [20]:
merged_df.columns

Index(['#Patient Identifier', 'Sample Identifier', 'Oncotree Code',
       'Cancer Type Detailed', 'Tumor Type',
       'Tissue Prospective Collection Indicator',
       'Tissue Retrospective Collection Indicator', 'Tissue Source Site Code',
       'Tumor Disease Anatomic Site', 'Aneuploidy Score', 'Sample Type',
       'MSI MANTIS Score', 'MSIsensor Score', 'Somatic Status',
       'TMB (nonsynonymous)', 'Tissue Source Site',
       'TCGA PanCanAtlas Cancer Type Acronym', 'Other Patient ID',
       'Diagnosis Age', 'Sex', 'Birth from Initial Pathologic Diagnosis Date',
       'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value',
       'Form completion date',
       'Neoadjuvant Therapy Type Administered Prior To Resection Text',
       'ICD-10 Classification',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code',
       'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code',
       'Informed consent verified', 'Prior Diagnosis',
       'In PanCan Pathway Analysis', 'Overall Survival (Months)'],
      dtype='object')

In [21]:
# Assuming your DataFrame is named 'df'
columns_to_keep = ['#Patient Identifier', 'Sample Identifier', 'Overall Survival (Months)']
used_df = merged_df[columns_to_keep]

In [22]:
used_df.head()

  #Patient Identifier Sample Identifier Overall Survival (Months)
0        TCGA-OR-A5J1   TCGA-OR-A5J1-01               44.54745701
1        TCGA-OR-A5J2   TCGA-OR-A5J2-01               55.13364237
2        TCGA-OR-A5J3   TCGA-OR-A5J3-01               68.74445212
3        TCGA-OR-A5J4   TCGA-OR-A5J4-01               13.90669691
4        TCGA-OR-A5J5   TCGA-OR-A5J5-01                11.9998685

In [23]:
used_df.shape

(92, 3)

In [24]:
df = pd.read_csv("/content/drive/MyDrive/gsoc data/data_mrna_seq_v2_rsem.txt", sep="\t")

In [25]:
patients = df.copy()
patients.head()

,Hugo_Symbol,Entrez_Gene_Id,TCGA-OR-A5J1-01,TCGA-OR-A5J2-01,TCGA-OR-A5J3-01,TCGA-OR-A5J5-01,TCGA-OR-A5J6-01,TCGA-OR-A5J7-01,TCGA-OR-A5J8-01,TCGA-OR-A5J9-01,...,TCGA-OR-A5LR-01,TCGA-OR-A5LS-01,TCGA-OR-A5LT-01,TCGA-OU-A5PI-01,TCGA-P6-A5OF-01,TCGA-PA-A5YG-01,TCGA-PK-A5H8-01,TCGA-PK-A5H9-01,TCGA-PK-A5HA-01,TCGA-PK-A5HB-01
0,NUDT18,79873,85.0144,165.884,309.2880,178.931,124.0660,283.5940,283.4650,123.7530,...,154.8120,176.1820,177.7210,157.925,524.4430,316.228,317.3020,232.0510,303.749,159.9840
1,SHC3,53358,97.5024,92.605,10.0726,49.574,5.5886,50.9426,36.0547,73.0957,...,46.0251,33.2035,75.6803,22.805,24.2472,113.731,46.8457,0.6979,192.944,50.5213
2,NCRNA00112,54089,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.000,0.0000
3,FAM49B,51571,671.9500,812.911,482.2990,466.305,1074.6800,594.4650,938.6660,592.9260,...,884.5190,272.4040,326.5310,263.398,931.5600,748.960,1241.1000,784.4370,897.464,718.9250
4,FMO6P,388714,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.4144,0.0000,...,0.0000,0.0000,0.0000,0.000,0.0000,0.000,0.0000,0.0000,0.000,0.4010

In [26]:
patients = patients.drop('Entrez_Gene_Id', axis=1)

In [27]:
patients.shape

(20531, 79)

In [28]:
patients.isnull().sum()

Hugo_Symbol        13
TCGA-OR-A5J1-01     0
TCGA-OR-A5J2-01     0
TCGA-OR-A5J3-01     0
TCGA-OR-A5J5-01     0
                   ..
TCGA-PA-A5YG-01     0
TCGA-PK-A5H8-01     0
TCGA-PK-A5H9-01     0
TCGA-PK-A5HA-01     0
TCGA-PK-A5HB-01     0
Length: 79, dtype: int64

In [29]:
patients = patients.dropna()

In [30]:
identifiers = patients['Hugo_Symbol'].unique()
print(len(identifiers))

20511

In [31]:
# Check for duplicate 'Hugo_Symbol' values
duplicates = patients['Hugo_Symbol'].duplicated(keep='last')

# Drop rows with duplicate 'Hugo_Symbol' or same symbol as the previous row
new_df = patients[~duplicates]

# Verify the updated DataFrame shape
print(new_df.shape)

(20511, 79)

In [32]:
new_df.shape

(20511, 79)

In [33]:
new_df_transposed = new_df.set_index('Hugo_Symbol').transpose()
new_df_transposed.head()

Hugo_Symbol,NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,ESPN,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
TCGA-OR-A5J1-01,85.0144,97.5024,0.0,671.950,0.0,2428.43,462.056,0.0,385.687,20.1729,...,0.0000,0.0,12.0077,0.0,17.2911,913.535,547.5500,363.112,1.9212,0.0
TCGA-OR-A5J2-01,165.8840,92.6050,0.0,812.911,0.0,5097.30,669.977,0.0,547.980,2.8184,...,0.4026,0.0,0.8053,0.0,268.9890,303.978,1793.3200,592.672,0.0000,0.0
TCGA-OR-A5J3-01,309.2880,10.0726,0.0,482.299,0.0,1615.76,514.294,0.0,1125.170,38.5128,...,0.5925,0.0,0.0000,0.0,689.4860,324.592,522.5890,456.821,0.0000,0.0
TCGA-OR-A5J5-01,178.9310,49.5740,0.0,466.305,0.0,1202.17,591.789,0.0,525.949,10.8443,...,0.0000,0.0,6.9713,0.0,54.2215,790.550,337.7230,484.895,1.5492,0.0
TCGA-OR-A5J6-01,124.0660,5.5886,0.0,1074.680,0.0,1424.53,805.312,0.0,279.987,3.9120,...,1.6766,0.0,1.1177,0.0,8.9417,291.550,9.5006,628.155,1.1177,0.0

In [37]:
# Merge the datasets based on the patient identifiers
patient_df = pd.merge(used_df, new_df_transposed, left_on='Sample Identifier', right_index=True)

In [38]:
patient_df.shape

(78, 20514)

In [39]:
patient_df.head()

,#Patient Identifier,Sample Identifier,Overall Survival (Months),NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
0,TCGA-OR-A5J1,TCGA-OR-A5J1-01,44.54745701,85.0144,97.5024,0.0,671.950,0.0,2428.43,462.056,...,0.0000,0.0,12.0077,0.0,17.2911,913.535,547.5500,363.112,1.9212,0.0
1,TCGA-OR-A5J2,TCGA-OR-A5J2-01,55.13364237,165.8840,92.6050,0.0,812.911,0.0,5097.30,669.977,...,0.4026,0.0,0.8053,0.0,268.9890,303.978,1793.3200,592.672,0.0000,0.0
2,TCGA-OR-A5J3,TCGA-OR-A5J3-01,68.74445212,309.2880,10.0726,0.0,482.299,0.0,1615.76,514.294,...,0.5925,0.0,0.0000,0.0,689.4860,324.592,522.5890,456.821,0.0000,0.0
4,TCGA-OR-A5J5,TCGA-OR-A5J5-01,11.9998685,178.9310,49.5740,0.0,466.305,0.0,1202.17,591.789,...,0.0000,0.0,6.9713,0.0,54.2215,790.550,337.7230,484.895,1.5492,0.0
5,TCGA-OR-A5J6,TCGA-OR-A5J6-01,88.86477956,124.0660,5.5886,0.0,1074.680,0.0,1424.53,805.312,...,1.6766,0.0,1.1177,0.0,8.9417,291.550,9.5006,628.155,1.1177,0.0

In [40]:
patient_df = patient_df.drop('#Patient Identifier', axis=1)

In [41]:
patient_df.set_index('Sample Identifier')

,Overall Survival (Months),NUDT18,SHC3,NCRNA00112,FAM49B,FMO6P,BAT2L2,SIRT1,MSLNL,ATG4A,...,SCARNA6,SNORD77,TLR10,GKN2,PCDHGB4,ZMAT5,AXIN2,LONRF1,KLHL10,C12orf36
Sample Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-OR-A5J1-01,44.54745701,85.0144,97.5024,0.0,671.950,0.000,2428.43,462.056,0.0000,385.687,...,0.0000,0.0,12.0077,0.000,17.2911,913.535,547.5500,363.112,1.9212,0.0
TCGA-OR-A5J2-01,55.13364237,165.8840,92.6050,0.0,812.911,0.000,5097.30,669.977,0.0000,547.980,...,0.4026,0.0,0.8053,0.000,268.9890,303.978,1793.3200,592.672,0.0000,0.0
TCGA-OR-A5J3-01,68.74445212,309.2880,10.0726,0.0,482.299,0.000,1615.76,514.294,0.0000,1125.170,...,0.5925,0.0,0.0000,0.000,689.4860,324.592,522.5890,456.821,0.0000,0.0
TCGA-OR-A5J5-01,11.9998685,178.9310,49.5740,0.0,466.305,0.000,1202.17,591.789,0.0000,525.949,...,0.0000,0.0,6.9713,0.000,54.2215,790.550,337.7230,484.895,1.5492,0.0
TCGA-OR-A5J6-01,88.86477956,124.0660,5.5886,0.0,1074.680,0.000,1424.53,805.312,0.0000,279.987,...,1.6766,0.0,1.1177,0.000,8.9417,291.550,9.5006,628.155,1.1177,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-PA-A5YG-01,24.85452214,316.2280,113.7310,0.0,748.960,0.000,1779.01,876.098,0.0000,732.316,...,0.0000,0.0,9.2464,0.000,780.8410,431.114,611.6500,657.420,0.4623,0.0
TCGA-PK-A5H8-01,119.1110234,317.3020,46.8457,0.0,1241.100,0.000,1908.81,492.192,0.6246,505.934,...,0.0000,0.0,4.9969,0.000,98.8445,250.462,62.4610,450.344,0.0000,0.0
TCGA-PK-A5H9-01,20.25183286,232.0510,0.6979,0.0,784.437,0.000,2699.82,756.870,0.0000,329.757,...,0.0000,0.0,2.0937,0.000,15.0048,249.987,45.7123,239.379,1.0468,0.0
TCGA-PK-A5HA-01,39.4844988,303.7490,192.9440,0.0,897.464,0.000,2393.05,732.084,0.0000,1101.980,...,0.5513,0.0,3.3076,0.000,1086.8500,247.393,192.3930,672.547,0.5513,0.0
TCGA-PK-A5HB-01,42.50912319,159.9840,50.5213,0.0,718.925,0.401,3359.26,1462.710,0.4010,884.523,...,0.0000,0.0,15.6375,0.401,94.2261,314.836,33.2799,121.091,0.4010,0.0

In [42]:
cBio = pd.DataFrame(patient_df)

In [43]:
cBio.to_csv('cBio.csv', index=False)